<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title >Le blog du Hacker</title>

    <!-- Feuilles de style externes -->
    <

    <!-- Feuilles de style de l'application -->

    <link rel="stylesheet" href="css/style.css">


</head>
<body>
    <!-- En-tête commune de l'application -->
    <header class="blog-header fixed-top">
        <h1><a href="index.php" > Le blog du Hacker</a></h1>

        <nav>
            <a href="admin.php"><i class="fa fa-cogs"></i> Exprimez vous </a>
        </nav>
    </header>

    <main>
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <?php include $template.'.phtml' ?>
    </main>

    <!-- Pied de page commun de l'application -->
    <footer class="blog-footer">
        <small>Le blog</small>
    </footer>
</body>
</html>